[colors.bright]
black = "#4c4c4b"
blue = "#a6cded"
cyan = "#94c9b2"
green = "#7aae98"
magenta = "#f7b4e1"
red = "#ffafa5"
white = "#eaeaea"
yellow = "#ffdeaa"

[colors.cursor]
cursor = "#a790d5"
text = "#1a1a19"

[colors.normal]
black = "#333332"
blue = "#8db4d4"
cyan = "#7bb099"
green = "#61957f"
magenta = "#de9bc8"
red = "#ff968c"
white = "#c7c7c7"
yellow = "#ffc591"

[colors.primary]
background = "#262626"
foreground = "#c7c7c7"

[font]
size = 16

[font.normal]
family = "Monaco Nerd Font"

[shell]
  program = "/bin/tmux"
  args = [ "-new-session", "-A", "-D", "-s", "main" ]
