#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

~/sh/autostart.sh

bspc wm --reorder-monitors HDMI-A-0 DisplayPort-0 
bspc monitor HDMI-A-0 -d 1 2
bspc monitor DisplayPort-0 -d 3 4 5 6
