export CC=clang
export CXX=clang++
export EDITOR=nvim
export TERMINAL=alacritty
export FILEMAN=thunar
export FILEMAN_TUI=vifm
export BROWSER=librewolf
export PATH=$PATH~/.cargo/bin

alias die="sudo paru -Syyu --noconfirm ; sudo poweroff"
alias rbt="sudo reboot"
alias ff="fastfetch"
alias s="sudo"
alias v="$EDITOR"
alias fm="$FILEMAN_TUI"
alias ls="ls -l --color"
alias ll="ls -lA --color"
alias mf="touch"
alias md="mkdir"
alias py="python"
alias mi="make install"
alias g="git"
alias gs="git status"
alias gcm="git commit -a -m"
alias ga="git add"
alias gpl="git pull"
alias gp="git push"
alias gi="git init"
alias gc="git clone"
alias gd="git diff"

export QT_QPA_PLATFORMTHEME=qt5ct
export _JAVA_AWT_WM_NONREPARENTING=1
